# Generated by Django 4.0.5 on 2022-06-04 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('enabled', models.BooleanField(default=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=100)),
                ('delay', models.FloatField(default=60)),
                ('add_to_queue', models.BooleanField(default=False)),
                ('add_to_playlist', models.BooleanField(default=True)),
                ('playlist_id', models.CharField(max_length=50)),
                ('banned_names', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotifyAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('access_token', models.CharField(max_length=250)),
                ('refresh_token', models.CharField(max_length=250)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.PositiveSmallIntegerField()),
                ('scope', models.CharField(max_length=250)),
                ('time', models.FloatField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('enabled', models.BooleanField(default=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('guild', models.CharField(max_length=200)),
                ('playlist_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
