# Generated by Django 4.0.5 on 2022-06-04 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordintegration',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 56, 28, 429417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 56, 28, 429417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spotifyauthorization',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 56, 28, 429417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitchintegration',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 56, 28, 429417, tzinfo=utc)),
        ),
    ]
