# Generated by Django 4.0.5 on 2022-06-04 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discordintegration_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordintegration',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotifyauthorization',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twitchintegration',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
