# Generated by Django 4.0.5 on 2022-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_spotifyauthorization_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchintegration',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
