# Generated by Django 4.0.5 on 2022-06-04 20:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_twitchintegration_banned_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchintegration',
            name='banned_names',
            field=models.JSONField(blank=True, default=list, null=True, validators=[]),
        ),
    ]
