# Generated by Django 4.0.5 on 2022-06-05 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_spotifyauthorization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyauthorization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify', to=settings.AUTH_USER_MODEL),
        ),
    ]
