# Generated by Django 4.0.5 on 2022-06-05 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_spotifyauthorization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchintegration',
            name='banned_names',
        ),
        migrations.CreateModel(
            name='TwitchIntegrationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banned', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_queued', models.DateTimeField(blank=True, default=None, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.twitchintegration')),
            ],
        ),
    ]
