# Generated by Django 4.0.5 on 2022-06-05 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_remove_twitchintegration_banned_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotifyauthorization',
            name='time_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twitchintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_integrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
