# Generated by Django 4.0.5 on 2022-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_discordintegration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchintegration',
            name='channel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
