# Generated by Django 4.0.5 on 2022-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_twitchintegration_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='administrator',
            field=models.BooleanField(default=False),
        ),
    ]
