# Generated by Django 4.0.5 on 2022-06-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_twitchintegration_delay_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchintegration',
            old_name='delay',
            new_name='queue_cooldown',
        ),
        migrations.RenameField(
            model_name='twitchintegration',
            old_name='delay_subscriber',
            new_name='queue_cooldown_subscriber',
        ),
    ]
