# Generated by Django 4.0.5 on 2022-06-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_delay_twitchintegration_queue_cooldown_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchintegrationuser',
            old_name='time_queued',
            new_name='time_cooldown',
        ),
    ]
