# Generated by Django 4.0.5 on 2022-06-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_time_queued_twitchintegrationuser_time_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchintegration',
            name='queue_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitchintegrationuser',
            name='manual_cooldown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchintegrationuser',
            name='queue_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
