# Generated by Django 4.0.5 on 2022-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_twitchintegration_queue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchintegration',
            name='subscribers_only',
            field=models.BooleanField(default=False),
        ),
    ]
