# Generated by Django 4.1.3 on 2022-12-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_twitchintegration_subscribers_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchintegration',
            old_name='channel',
            new_name='twitch_login',
        ),
        migrations.AddField(
            model_name='twitchintegration',
            name='twitch_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
