# Generated by Django 4.1.3 on 2022-12-07 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_twitchauthorization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchintegration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_integration', to=settings.AUTH_USER_MODEL),
        ),
    ]
